### ISSUE TITLE
Minimal toolchain build failure

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#3210] opened 2016-06-15 10:56 UTC
I've made the following two easyconfigs for local use (which with some cleanup will be submitted upstream):

```
# This file is an EasyBuild reciPY as per https://github.com/hpcugent/easybuild
# Author: Adam Huffman
# The Francis Crick Institute
easyblock = 'PythonPackage'

name = 'cnvkit'
version = '0.7.3'
versionsuffix = '-Python-%(pyver)s'

homepage = 'http://cnvkit.readthedocs.org/'
description = """Copy number variant detection from targeted DNA sequencing"""

toolchain = {'name': 'foss', 'version': '2015b'}

sources = ['v%(version)s.tar.gz']
source_urls = ['https://github.com/etal/cnvkit/archive']

dependencies = [
    ('Python', '2.7.10'),
    ('Biopython', '1.66', versionsuffix),
    ('%(name)s-bundle', '%(version)s', versionsuffix),
    ('R-bundle-%(name)s', '0.1', '-R-3.2.3'),
]

sanity_check_paths = {
    'files': ['bin/cnvkit.py', 'bin/reference2targets.py', 'bin/vcf_sample_filter.py',
              'lib/python%(pyshortver)s/site-packages/CNVkit-%(version)s-py%(pyshortver)s.egg'],
    'dirs': []
}

options = {'modulename': 'cnvlib'}

sanity_check_commands = [ 'cd test; make' ]

moduleclass = 'bio'
```

which relies on:

```
# This file is an EasyBuild reciPY as per https://github.com/hpcugent/easybuild
# Author: Adam Huffman
# The Francis Crick Institute
easyblock = 'Bundle'

name = 'cnvkit-bundle'
version = '0.7.3'
versionsuffix = '-Python-%(pyver)s'

homepage = 'http://cnvkit.readthedocs.org/en/latest/index.html'
description = """CNVkit is a Python library and command-line software toolkit to infer and
 visualize copy number from targeted DNA sequencing data. It is designed for use with hybrid
 capture, including both whole-exome and custom target panels, and short-read sequencing
 platforms such as Illumina and Ion Torrent. This is a bundle to provide dependencies for cnvkit
 that aren't available in the standard EasyBuild Python."""

toolchain = {'name': 'foss', 'version': '2015b'}

# this is a bundle of Python packages
exts_defaultclass = 'PythonPackage'

dependencies = [
    ('Python', '2.7.10'),
]

exts_list = [
    ('reportlab', '3.3.0', {
        'source_urls': ['https://pypi.python.org/packages/source/r/reportlab'],
    }),
    ('PyVCF', '0.6.8', {
        'modulename': 'vcf',
        'source_urls': ['https://pypi.python.org/packages/source/P/PyVCF'],
    }),
    ('pysam', '0.9.0', {
        'source_urls': ['https://pypi.python.org/packages/source/p/pysam'],
    }),
]

# specify that Bundle easyblock should run a full sanity check, rather than just trying to load the module
full_sanity_check = True

sanity_check_paths = {
    'files': [],
    'dirs': ['lib/python%(pyshortver)s/site-packages'],
}

modextrapaths = {'PYTHONPATH': ['lib/python%(pyshortver)s/site-packages']}

moduleclass = 'bio'
```

These two work on one of my test servers.

However, I'm trying to install them on a fresh cloud instance with minimal-toolchains enabled, and the build fails:

```
[adam@lung-login ~]$ eb ~/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb -dr
== temporary log file in case of crash /tmp/eb-3Kzofr/easybuild-QsCCIE.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '-Python-%(pyver)s', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Biopython', 'short_mod_name': None, 'version': '1.66', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}
```

Here is the `Biopython` easyconfig that it should be using:

```
##
# This file is an EasyBuild reciPY as per https://github.com/hpcugent/easybuild
#
# Copyright:: Copyright 2012-2013 The Cyprus Institute
# Authors::   Andreas Panteli <a.panteli@cyi.ac.cy>, Thekla Loizou <t.loizou@cyi.ac.cy>, George Tsouloupas <g.tsouloupas@cyi.ac.cy>
# License::   MIT/GPL
#
##
easyblock = "PythonPackage"

name = 'Biopython'
version = '1.66'
versionsuffix = '-Python-%(pyver)s'

homepage = 'http://www.biopython.org'
description = """Biopython is a set of freely available tools for biological computation written
in Python by an international team of developers. It is a distributed collaborative effort to
develop Python libraries and applications which address the needs of current and future work in
bioinformatics. """

toolchain = {'name': 'foss', 'version': '2015b'}

source_urls = ['http://biopython.org/DIST']
sources = ['%(namelower)s-%(version)s.tar.gz']

dependencies = [
    ('Python', '2.7.10'),
]

sanity_check_paths = {
    'files': ['lib/python%(pyshortver)s/site-packages/biopython-%(version)s-py%(pyshortver)s.egg-info'],
    'dirs': ['lib/python%(pyshortver)s/site-packages/Bio',
             'lib/python%(pyshortver)s/site-packages/BioSQL']
}

options = {'modulename': 'Bio'}

moduleclass = 'bio'
```

**Comment by verdurin** [comment] 2016-06-15 12:16
Seeing the same thing with a locally-modified `R-3.2.1` easyconfig:

```
[adam@lung-login ~]$ eb ~/src/github/easybuild-easyconfigs-devel/R-3.2.1-foss-2015b-x11-png.eb -dr
== temporary log file in case of crash /tmp/eb-ZLM7BC/easybuild-oIltdL.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/R-3.2.1-foss-2015b-x11-png.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Tk', 'short_mod_name': None, 'version': '8.6.4', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}
```

The dependencies section of the R easyconfig is:

```
dependencies = [
    ('libreadline', '6.3'),
    ('ncurses', '5.9'),
    ('libpng', '1.6.17'),  # for plotting in R
    ('libjpeg-turbo', '1.4.1'),  # for plottting in R
    ('Java', '1.8.0_45', '', True),  # Java bindings are built if Java is found, might as well provide it
    ('Tcl', '8.6.4'),  # for tcltk
    ('Tk', '8.6.4'),  # for tcltk
    ('cURL', '7.43.0'),  # for RCurl
    ('libxml2', '2.9.2'),  # for XML
]
```

**Comment by boegel** [comment] 2016-06-15 12:48
@verdurin How is EasyBuild configured here exactly (what does `eb --show-config` spit out)?

Also, a debug log would be useful I think (it seems like we're missing some info in the error message to pinpoint the issue).

cc @ocaisa, @damianam

**Comment by verdurin** [comment] 2016-06-15 12:50
```
[adam@lung-login profile.d]$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath          (F) = /srv/data/sw/eb/build
installpath        (F) = /srv/data/sw/eb
minimal-toolchains (F) = True
modules-tool       (F) = Lmod
packagepath        (F) = /srv/data/sw/eb/packages
prefix             (F) = /srv/data/sw/eb
repositorypath     (F) = /srv/data/sw/eb/ebfiles_repo
robot-paths        (D) = /srv/data/sw/eb/software/EasyBuild/2.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.1-py2.7.egg/easybuild/easyconfigs
sourcepath         (F) = /srv/data/sw/eb/sources
```

**Comment by verdurin** [comment] 2016-06-15 12:52
[cnvkit-minimal-toolchain-debug-log.zip](https://github.com/hpcugent/easybuild-easyconfigs/files/316130/cnvkit-minimal-toolchain-debug-log.zip)

**Comment by verdurin** [comment] 2016-06-15 12:53
I host these local easyconfigs here:

https://github.com/verdurin/easybuild-easyconfigs-devel

**Comment by boegel** [comment] 2016-06-15 13:03
@verdurin you need to make sure that the robot can pick up any additional easyconfig files that are needed to resolve all dependencies, which doesn't seem to be the case here?

**Comment by ocaisa** [comment] 2016-06-15 14:12
@verdurin This is an old bug that actually comes from the HMNS. The problem is that eb is looking for an eb file that doesn't exist:
```
== 2016-06-15 12:51:16,155 easyconfig.py:1261 DEBUG Checking easyconfig path /srv/data/sw/eb/software/EasyBuild/2.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.1-py2.7.egg/easybuild/easyconfigs/Biopython-1.66-foss-2015b-Python-%(pyver)s.eb
```
The reason is that the hierarchical scheme goes looking for the easyconfig before the substitutions (like `pyver`) have been made in the framework. The workaround is to not use the substitutions in the name/version/versionsuffix/toolchain...very tedious for python versionsuffixes

**Comment by boegel** [comment] 2016-06-15 14:18
@ocaisa Was this reported earlier? Because I think that can be fixed...

Also, it doesn't explain the similar issue with the `Tk` dep?

**Comment by ocaisa** [comment] 2016-06-15 14:39
Discussed in https://github.com/hpcugent/easybuild-easyconfigs/pull/2104

**Comment by ocaisa** [comment] 2016-06-15 14:44
I don't see an issue with the Tk dep...

**Comment by ocaisa** [comment] 2016-06-15 16:42
In your Biopython easyconfig change
```
versionsuffix = '-Python-%(pyver)s'
```
to
```
versionsuffix = '-Python-2.7.10'
```
to side step the bug I mention above

**Comment by verdurin** [comment] 2016-06-15 16:52
That didn't fix it. This happened when I altered Biopython and rebuilt it, then tried cnvkit again:

```
[adam@lung-login easybuild-easyconfigs-devel]$ eb cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb -dr
== temporary log file in case of crash /tmp/eb-uwa5yh/easybuild-9OWaru.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '-Python-%(pyver)s', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Biopython', 'short_mod_name': None, 'version': '1.66', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}
```

I altered the cnvkit easyconfig to use a hardcoded Python version and then saw this error:

```
[adam@lung-login easybuild-easyconfigs-devel]$ eb cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb -dr
== temporary log file in case of crash /tmp/eb-VgM2qi/easybuild-9xi7qe.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '-Python-2.7.10', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Biopython', 'short_mod_name': None, 'version': '1.66', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}
```

**Comment by ocaisa** [comment] 2016-06-15 17:14
I think the easyconfig you installed is not the one in your robot path, use
--robot=./
(assuming the biopython easyconfig is in your current path) and the robot will pick up the version with the hardcoded suffix

On 15 Jun 2016 6:52 p.m., "Adam Huffman" <notifications@github.com<mailto:notifications@github.com>> wrote:

That didn't fix it. This happened when I altered Biopython and rebuilt it, then tried cnvkit again:

[adam@lung-login easybuild-easyconfigs-devel]$ eb cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb -dr
== temporary log file in case of crash /tmp/eb-uwa5yh/easybuild-9OWaru.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '-Python-%(pyver)s', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Biopython', 'short_mod_name': None, 'version': '1.66', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}


I altered the cnvkit easyconfig to use a hardcoded Python version and then saw this error:

[adam@lung-login easybuild-easyconfigs-devel]$ eb cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb -dr
== temporary log file in case of crash /tmp/eb-VgM2qi/easybuild-9xi7qe.log
ERROR: Failed to process easyconfig /home/adam/src/github/easybuild-easyconfigs-devel/cnvkit-0.7.3-foss-2015b-Python-2.7.10.eb: No easyconfig for {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': False, 'versionsuffix': '-Python-2.7.10', 'external_module': False, 'dummy': False, 'toolchain': None, 'name': 'Biopython', 'short_mod_name': None, 'version': '1.66', 'hidden': False} that matches toolchain hierarchy generated by {'version': '2015b', 'name': 'foss'}


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hpcugent/easybuild-easyconfigs/issues/3210#issuecomment-226249205>, or mute the thread<https://github.com/notifications/unsubscribe/ADqZtdy16S52NIe_C5WkU8CF7mXMT0N3ks5qMC3LgaJpZM4I2PDX>.


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by verdurin** [comment] 2016-06-15 17:29
Yes, I've made some progress by spelling out all the embedded `versionsuffix` etc. macros.

Still complaining about the R bundle. Bah.

**Comment by boegel** [comment] 2016-06-15 19:42
@verdurin I'm not convinced that the issue with R is the same problem...

**Comment by verdurin** [comment] 2016-06-16 05:37
@boegel, @ocaisa - a combination of using the suggested robot settings (I'd been using `--robot-paths`, wrongly) and laboriously expanding further versionsuffix entries I'd missed has fixed all the problems so far.

**Comment by verdurin** [comment] 2016-06-16 08:49
I should point out that I haven't enabled HierarchicalMNS, just minimal toolchains.

**Comment by boegel** [comment] 2016-06-16 08:59
@verdurin OK, but the issue is probably the same as #1402, deep down... I'll see what I can do to fix it.

**Comment by boegel** [comment] 2016-06-16 18:36
@verdurin This bug should be fixed in https://github.com/hpcugent/easybuild-framework/pull/1812, please verify?

**Comment by boegel** [comment] 2016-06-20 16:45
fixed with https://github.com/hpcugent/easybuild-framework/pull/1812

**Closed by boegel** 2016-06-20 16:45 UTC
