### ISSUE TITLE
Missing X dependency for R-Bioconductor

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#1845] opened 2015-08-12 14:19 UTC
[this is my first ever use of EasyBuild, so please forgive any mistakes...]

I've been trying to install the goolf version of Bioconductor. At first I was missing Java but I installed that manually. Now I've seen a problem with Tk:

```
gcc -c -O2 -I/srv/data/sw/eb/software/Tcl/8.6.4-goolf-1.7.20/include -pipe -I/srv/data/sw/eb/software/OpenBLAS/0.2.13-GCC-4.8.4-LAPACK-3.5.0/include -I/srv/data/sw/eb/software/ScaLAPACK/2.0.2-gompi-1.7.20-OpenBLAS-0.2.13-LAPACK-3.5.0/include -I/srv/data/sw/eb/software/FFTW/3.3.4-gompi-1.7.20/include -I/srv/data/sw/eb/software/Tcl/8.6.4-goolf-1.7.20/include -Wall -fPIC -DBUILD_tk -I/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../unix -I/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic -I/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../bitmaps -I/home/operations/.local/easybuild/build/Tcl/8.6.4/goolf-1.7.20/tcl8.6.4/generic -I/home/operations/.local/easybuild/build/Tcl/8.6.4/goolf-1.7.20/tcl8.6.4/unix  -DPACKAGE_NAME=\"tk\" -DPACKAGE_TARNAME=\"tk\" -DPACKAGE_VERSION=\"8.6\" -DPACKAGE_STRING=\"tk\ 8.6\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAVE_PTHREAD_ATTR_SETSTACKSIZE=1 -DHAVE_PTHREAD_ATFORK=1 -DTCL_THREADS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -DTCL_SHLIB_EXT=\".so\" -DNDEBUG=1 -DTCL_CFG_OPTIMIZED=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_INTPTR_T=1 -DHAVE_UINTPTR_T=1 -DHAVE_PW_GECOS=1 -DXKEYCODETOKEYSYM_IS_DEPRECATED=1      -DTCL_NO_DEPRECATED  -DUSE_TCL_STUBS /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkBusy.c
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/ttk/ttkStubLib.c:9:0:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk3d.c:14:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkStubLib.c:14:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tk3d.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [ttkStubLib.o] Error 1
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkAtom.c:16:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkArgv.c:14:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkStubLib.o] Error 1
make: *** [tkAtom.o] Error 1
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkBind.c:15:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkArgv.o] Error 1
make: *** [tkBind.o] Error 1
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkBitmap.c:15:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
In file included from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tkBusy.c:15:
/home/operations/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkBitmap.o] Error 1
make: *** [tkBusy.o] Error 1
 (at easybuild/software/EasyBuild/2.2.0/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/run.py:360 in parse_cmd_output)
== 2015-08-12 14:10:44,177 main.easyblock WARNING build failed (first 300 chars): cmd " make -j 8 " exited with exitcode 2 and output:
gcc -c -O2 -I/srv/data/sw/eb/software/Tcl/8.6.4-goolf-1.7.20/include -pipe -I/srv/data/sw/eb/software/OpenBLAS/0.2.13-GCC-4.8.4-LAPACK-3.5.0/include -I/srv/data/sw/eb/software/ScaLAPACK/2.0.2-gompi-1.7.20-OpenBLAS-0.2.13-LAPACK-3.5.0/include -I/sr
== 2015-08-12 14:10:44,177 main.ConfigureMake INFO Closing log for application name Tk version 8.6.4
```

**Comment by verdurin** [comment] 2015-08-12 14:21
This is the command I used:

eb R-bundle-Bioconductor-3.1-goolf-1.7.20-R-3.2.0.eb --robot

on a CentOS 7.1 VM.

eb --version
This is EasyBuild 2.2.0 (framework: 2.2.0, easyblocks: 2.2.0)

**Comment by boegel** [comment] 2015-08-12 14:48
Can you try and figure out whether `--without-x` was being used in the configure command used for Tk?

Hopefully http://easybuild.readthedocs.org/en/latest/Logfiles.html can help you with that.

**Comment by verdurin** [comment] 2015-08-12 15:00
Yes, it was:

== 2015-08-12 14:10:44,066 main.run INFO cmd " ./configure --prefix=/srv/data/sw/eb/software/Tk/8.6.4-goolf-1.7.20-no-X11 --enable-threads --with-tcl=$EBROOTTCL/lib --without-x CFLAGS="-I$EBROOTTCL/include"" exited with exitcode 0 and output:

**Comment by verdurin** [comment] 2015-08-12 15:01
Later on in the configure output it says:

checking for X... disabled
checking for X11 header files... couldn't find any!
checking for X11 libraries... checking for XCreateWindow in -lXwindow... no
could not find any!  Using -lX11.

**Comment by jmkekala** [comment] 2015-10-13 10:59
sama problem here:

checking for X... disabled
checking for X11 header files... couldn't find any!
checking for X11 libraries... checking for XCreateWindow in -lXwindow... no
could not find any!  Using -lX11.
checking for main in -lXbsd... no
checking whether to use xft... no
checking for X11/XKBlib.h... no
checking whether XKeycodeToKeysym is deprecated... yes
checking whether to try to use XScreenSaver... yes
checking for X11/extensions/scrnsaver.h... no
checking for XScreenSaverQueryInfo... no
checking for XScreenSaverQueryInfo in -lXext... no
checking for XScreenSaverQueryInfo in -lXss... no
checking whether char is unsigned... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tkConfig.sh
config.status: creating tk.pc

####

In file included from /tmp/easybuild/Tk/8.6.4/foss-2015b-no-X11/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /tmp/easybuild/Tk/8.6.4/foss-2015b-no-X11/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /tmp/easybuild/Tk/8.6.4/foss-2015b-no-X11/tk8.6.4/unix/../generic/tkStubLib.c:14:
/tmp/easybuild/Tk/8.6.4/foss-2015b-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>

**Comment by boegel** [comment] 2016-03-15 08:04
This is a duplicate of #2261, where more information is available on fixing this issue.

**Comment by boegel** [comment] 2016-09-19 12:56
let's follow up via #2261

**Closed by boegel** 2016-09-19 12:56 UTC
