### ISSUE TITLE
Problem building GCC/4.9.3-binutils-2.25

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#2188] opened 2015-12-05 00:34 UTC
On a F23 system with EB 2.4.0:

```
== building and installing GCC/4.9.3-binutils-2.25...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
 == FAILED: Installation ended unsuccessfully (build directory: /home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25): build failed (first 300 chars): cmd " make -j 4  bootstrap " exited with
exitcode 2 and output:
echo stage3 > stage_final
make[1]: Entering directory '/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj'
make[2]: Entering directory '/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9
== Results of the build can be found in the log file /tmp/eb-flSkAK/easybuild-GCC-4.9.3-20151204.233536.pbHgs.log
ERROR: Build of /home/adam/.local/easybuild/software/EasyBuild/2.4.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.4.0-py2.7.egg/easybuild/easyconfigs/g/GCC/GCC-4.9.3-binutils-2.25.eb failed (err: 'build failed (first 300 chars): cmd " make -j 4  bootstrap " exited with exitcode 2 and output:\necho stage3 > stage_final\nmake[1]: Entering directory \'/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj\'\nmake[2]: Entering directory \'/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9')
```

There are errors like this in the log:

```
make[1]: Entering directory '/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj'
Checking multilib configuration for libgomp...
Checking multilib configuration for libssp...
Checking multilib configuration for libquadmath...
mkdir -p -- x86_64-unknown-linux-gnu/libssp
Configuring in ./fixincludes
mkdir -p -- x86_64-unknown-linux-gnu/libquadmath
Checking multilib configuration for libatomic...
mkdir -p -- x86_64-unknown-linux-gnu/libatomic
Configuring in x86_64-unknown-linux-gnu/libssp
Configuring in x86_64-unknown-linux-gnu/libquadmath
Configuring in x86_64-unknown-linux-gnu/libatomic
configure: creating cache ./config.cache
configure: creating cache ./config.cache
configure: creating cache ./config.cache
configure: creating cache ./config.cache
checking for --enable-version-specific-runtime-libs... no
checking for --enable-generated-files-in-srcdir... no
checking build system type... checking build system type... checking build system type... checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnu
checking target system type... checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for x86_64-unknown-linux-gnu-gcc... checking whether build environment is sane... /home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj/./gcc/xgcc -B/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj/./gcc/ -B/home/adam/.local/easybuild/software/GCC/4.9.3-binutils-2.25/x86_64-unknown-linux-gnu/bin/ -B/home/adam/.local/easybuild/software/GCC/4.9.3-binutils-2.25/x86_64-unknown-linux-gnu/lib/ -isystem /home/adam/.local/easybuild/software/GCC/4.9.3-binutils-2.25/x86_64-unknown-linux-gnu/include -isystem /home/adam/.local/easybuild/software/GCC/4.9.3-binutils-2.25/x86_64-unknown-linux-gnu/sys-include
x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... checking for C compiler default output file name...
configure: error: in `/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj/fixincludes':
configure: error: C compiler cannot create executables
See `config.log' for more details.
Makefile:3377: recipe for target 'configure-fixincludes' failed
make[1]: *** [configure-fixincludes] Error 1
make[1]: *** Waiting for unfinished jobs....
yes
yes
yes
```

**Comment by boegel** [comment] 2015-12-05 07:51
@verdurin: do you still have `/home/adam/.local/easybuild/build/GCC/4.9.3/dummy--binutils-2.25/gcc-4.9.3/obj/fixincludes/config.log` around? Can you share it's contents (maybe via a gist)?

**Comment by verdurin** [comment] 2015-12-05 08:49
@boegel - it's here:

https://gist.github.com/verdurin/a467ff65f748a72ec74e

**Comment by wpoely86** [comment] 2015-12-10 09:48
Okay, this is weird. It's a Fedora 23 system? I think we're hitting this:
https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths
Which is weird. The system `libstdc++` has `GLIBCXX_3.4.21` so not sure what the problem is here. Will try to reproduce.

**Comment by verdurin** [comment] 2015-12-12 11:58
Yes, Fedora 23.

```
 rpm -q glibc libstdc++
glibc-2.22-6.fc23.x86_64
libstdc++-5.3.1-2.fc23.x86_64
```

**Comment by wpoely86** [comment] 2015-12-12 20:21
@verdurin Can you rebuild `binutils` with the following easyconfig: https://gist.github.com/0f247818f344fd688cf3

and then try building `GCC` again?

**Comment by boegel** [comment] 2015-12-12 20:26
@wpoely86: what's the key change there?

**Comment by wpoely86** [comment] 2015-12-12 20:34
@boegel `rpath` for system `glibc` in the `binutils` used for building `gcc`

**Comment by verdurin** [comment] 2015-12-13 00:35
@wpoely86: Yes, that worked. I was able to build `HPL` for `foss2015b`, including that version of `GCC`, after building the custom `binutils`.

**Comment by boegel** [comment] 2015-12-13 09:38
OK, that's good.

@wpoely86: PR for this? Should we also rpath `/lib` to be sure?

**Comment by wpoely86** [comment] 2015-12-13 14:03
`/lib` is only for 32 bit on Fedora. In principle, we should add both `/usr/lib64` and `/lib64` but for Fedora, these are the same.

**Comment by boegel** [comment] 2015-12-13 16:37
@wpoely86: I suggest you open a PR that uses rpath for both `lib64` and `/usr/lib64`? Would be nice to get that in for EB v2.5.0...

**Comment by boegel** [comment] 2015-12-15 17:57
@wpoely86: ping on PR for this modified binutils easyconfig?

**Comment by wpoely86** [comment] 2015-12-15 20:17
Can be found in #2228

**Comment by boegel** [comment] 2015-12-15 22:58
OK, let's close this one then (we have enough open issues as is, I like to avoid having duplicates).

Do mention this issue ID in the description of #2228 though!

**Closed** 2015-12-16 09:28 UTC
